version: "3"

services:
  app:
    image: node:latest
    command: npm start
    expose:
      - 3000
    working_dir: /app
    volumes:
      - .:/app

  webpack:
    image: node:latest
    command: npm run assets
    ports:
      - 8080:8080
    working_dir: /app
    volumes:
      - .:/app:cached
